import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import useWindowDimensions from "../hooks/useWindowDimensions";
import styles from "../styles/Home.module.css";
import { SSRProvider } from "@react-aria/ssr";

const Home: NextPage = () => {
  const { width, height } = useWindowDimensions();

  useEffect(() => {
    console.log({ width, height });
  }, [width, height]);

  console.log(width);

  //if (!width && !height) return <div> loading</div>;

  const text = "screen size: ";

  return (
    <SSRProvider>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div> {text}</div>
      </div>
    </SSRProvider>
  );
};

export default Home;
