import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import useWindowDimensions from "../hooks/useWindowDimensions";
import styles from "../styles/Home.module.css";
import { SSRProvider } from "@react-aria/ssr";

const Home: NextPage = () => {
  const { width, height } = useWindowDimensions();

 

 

  //if (!width && !height) return <div> loading</div>;

  const text = "screen size: ";

  return (
    <SSRProvider>
      <div className={styles.container}>
        <Head>
          <title>Home pae</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1> Home</h1>
        <div> lorem fdklfkd fdbfd fdfd fd fdufvd fd fd fd;f fdvfd </div>
      </div>
    </SSRProvider>
  );
};

export default Home;
